framework:
    messenger:
        transports:
#            async: '%env(MESSENGER_TRANSPORT_DSN)%'
#            async: 'amqp://guest:guest@rabbitmq-container:5672/%2f/messages'
            async: 'amqp://guest:guest@localhost:5672/%2f/messages'
            # sync: 'sync://'

        routing:
            'App\Message\ScrapMessage': async
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async